apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- daskKubernetes-role.yaml
- workflow-role.yaml
- workflows-default-serviceaccount.yaml
- workflows-default-rolebinding.yaml
- workflows-default-dask-rolebinding.yaml
- https://github.com/argoproj/argo/manifests/cluster-install?ref=v2.12.3
