apiVersion: v1
kind: ConfigMap
metadata:
    # if you want to use this config map by default - name it "artifact-repositories" 
  name: artifact-repositories
  annotations:
    # v3.0 and after - if you want to use a specific key, put that's key into this annotation 
    workflows.argoproj.io/default-artifact-repository: default-v1
data:
  default-v1: |
    s3:
      bucket: repo
      endpoint: minio:9000
      insecure: true
      accessKeySecret:
        name: miniocreds-secret
        key: accesskey
      secretKeySecret:
        name: miniocreds-secret
        key: secretkey
      keyFormat: "{{workflow.name}}/{{pod.name}}"
