apiVersion: v1
kind: ConfigMap
metadata:
  name: workflow-controller-configmap
data:
  artifactRepository: |
    s3:
      bucket: repo
      endpoint: minio:9000
      insecure: true
      accessKeySecret:
        name: miniocreds-secret
        key: accesskey
      secretKeySecret:
        name: miniocreds-secret
        key: secretkey
      keyFormat: "{{workflow.name}}/{{pod.name}}"
